openapi: 3.0.3
info:
  title: Employee Management API
  version: 1.0.0
  description: API for managing employees and their devices.
paths:
  /employees:
    get:
      summary: List all employees with their devices
      operationId: listEmployees
      responses:
        '200':
          description: A list of employees
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EmployeeApiDto'
        '400':
          description: Bad request, possibly validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'

    post:
      summary: Create a new employee
      operationId: createEmployee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeApiDto'
      responses:
        '201':
          description: Employee created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeApiDto'
        '400':
          description: Bad request, validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'

  /employees/{employeeId}:
    get:
      summary: Get an employee by ID with their devices
      operationId: getEmployee
      parameters:
        - name: employeeId
          in: path
          required: true
          description: ID of the employee
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: The employee with their devices
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeApiDto'
        '404':
          description: Employee not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'

    put:
      summary: Update an employee by ID
      operationId: updateEmployee
      parameters:
        - name: employeeId
          in: path
          required: true
          description: ID of the employee to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeApiDto'
      responses:
        '200':
          description: Employee updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeApiDto'
        '400':
          description: Bad request, validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        '404':
          description: Employee not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'

    delete:
      summary: Delete an employee by ID
      operationId: deleteEmployee
      parameters:
        - name: employeeId
          in: path
          required: true
          description: ID of the employee to delete
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Employee deleted successfully
        '404':
          description: Employee not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'

components:
  schemas:
    EmployeeApiDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        surname:
          type: string
        lastname:
          type: string
        lastname2:
          type: string
        dateOfBirth:
          type: string
          format: date
        devices:
          type: array
          items:
            $ref: '#/components/schemas/DeviceApiDto'

    DeviceApiDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        employeeId:
          type: integer
          format: int64
        name:
          type: string
        details:
          type: string

    ProblemDetail:
      type: object
      properties:
        type:
          type: string
          description: A URI identifying the problem type
        title:
          type: string
          description: A short, human-readable summary of the problem
        status:
          type: integer
          description: The HTTP status code associated with the problem
        detail:
          type: string
          description: A detailed explanation of the problem
        instance:
          type: string
          description: A URI that identifies the specific occurrence of the problem
