spring:
  application:
    name: employees-spring

  datasource:
    url: jdbc:h2:mem:sms_notification_memory_db;Mode=MariaDB
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
