spring:
  application:
    name: employees-spring

  datasource:
    url: jdbc:mariadb://emp_track_db:3306/emp_track
    username: employeeManager
    password: Almafa1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
